services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: oreopet
      POSTGRES_USER: oreo
      POSTGRES_PASSWORD: oreo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ../backend
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ../frontend
    environment:
     - VITE_BACKEND_URL=http://backend:8080
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  pgdata:
